<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from civirfm/xml/schema/CRM/Civirfm/ContactRfm.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:f142b1e309c6253d44c64c5b7f123eaa)
 */
use CRM_Civirfm_ExtensionUtil as E;

/**
 * Database access object for the ContactRfm entity.
 */
class CRM_Civirfm_DAO_ContactRfm extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_contact_rfm';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ContactRfm ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contact - should be unique within table
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Date of last relevant contribution
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $date_last_contrib;

  /**
   * Date of first relevant contribution
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $date_first_contrib;

  /**
   * Date of last calculation of RFM values
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $date_calculated;

  /**
   * Number of gifts in RFM period
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $frequency;

  /**
   * Average gift value in RFM period
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $monetary;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_contact_rfm';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Contact Rfms') : E::ts('Contact Rfm');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ContactRfm ID'),
          'required' => TRUE,
          'where' => 'civicrm_contact_rfm.id',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact - should be unique within table'),
          'where' => 'civicrm_contact_rfm.contact_id',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'date_last_contrib' => [
          'name' => 'date_last_contrib',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Date Last Contrib'),
          'description' => E::ts('Date of last relevant contribution'),
          'required' => FALSE,
          'where' => 'civicrm_contact_rfm.date_last_contrib',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'add' => NULL,
        ],
        'date_first_contrib' => [
          'name' => 'date_first_contrib',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Date First Contrib'),
          'description' => E::ts('Date of first relevant contribution'),
          'required' => FALSE,
          'where' => 'civicrm_contact_rfm.date_first_contrib',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'add' => NULL,
        ],
        'date_calculated' => [
          'name' => 'date_calculated',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Date Calculated'),
          'description' => E::ts('Date of last calculation of RFM values'),
          'required' => FALSE,
          'where' => 'civicrm_contact_rfm.date_calculated',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'add' => NULL,
        ],
        'frequency' => [
          'name' => 'frequency',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Frequency'),
          'description' => E::ts('Number of gifts in RFM period'),
          'where' => 'civicrm_contact_rfm.frequency',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'add' => NULL,
        ],
        'monetary' => [
          'name' => 'monetary',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Monetary'),
          'description' => E::ts('Average gift value in RFM period'),
          'where' => 'civicrm_contact_rfm.monetary',
          'table_name' => 'civicrm_contact_rfm',
          'entity' => 'ContactRfm',
          'bao' => 'CRM_Civirfm_DAO_ContactRfm',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contact_rfm', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contact_rfm', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
