-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_contact_rfm`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contact_rfm
-- *
-- * RFM data for CiviCRM contacts
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contact_rfm` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ContactRfm ID',
  `contact_id` int unsigned COMMENT 'FK to Contact - should be unique within table',
  `date_last_contrib` timestamp NULL COMMENT 'Date of last relevant contribution',
  `date_first_contrib` timestamp NULL COMMENT 'Date of first relevant contribution',
  `date_calculated` timestamp NULL COMMENT 'Date of last calculation of RFM values',
  `frequency` int unsigned COMMENT 'Number of gifts in RFM period',
  `monetary` int unsigned COMMENT 'Average gift value in RFM period',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_contact_rfm_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
